language: php

php:
  - 7.0

before_script:
  - composer self-update
  - npm install -g gulp-cli

script:
  - bash sync-laravel.com -h
  - bash sync-laravel.com laravel.com
  - bash sync-laravel.com laravel.com upgrade
  - bash sync-laravel.com laravel.com status
  - bash sync-laravel.com laravel.com skip-docs
  - bash sync-laravel.com laravel.com skip-api
  - bash sync-laravel.com laravel.com clean

os:
  - linux
  # - osx
